# Generated by Django 3.1.4 on 2020-12-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
