# Generated by Django 3.1.4 on 2020-12-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20201222_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
